# fly.toml app configuration file generated for nova-crm-backend on 2025-08-28T11:16:44-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nova-crm-backend"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"   # <— add this line (path relative to this fly.toml)

[http_service]
  internal_port = 5001            # ⇐ your server.listen(PORT) must be 5001
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    soft_limit = 200
    hard_limit = 250

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443

  # Health check: make sure your app serves 200 on /healthz
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/healthz"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1